language: perl
perl:
- '5.20'
before_install:
- git config --global user.name "TravisCI"
- git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
- git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew
- export PATH=~/.rakudobrew/bin:$PATH
- rakudobrew triple
- alias eval="exit 0;"
- alias cpanm="exit 0;"
before_script:
- panda list --installed --verbose
script:
- prove -v -e "perl6 --ll-exception -Ilib" t/
