language: perl
perl:
- '5.20'
before_install:
- git config --global user.name "TravisCI"
- git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
- git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew
- export PATH=~/.rakudobrew/bin:$PATH
- rakudobrew triple
- dir
- ls
- rakudobrew build-panda
- dir
- ls
- panda install HTTP::UserAgent --notests
before_script:
- dir
- ls
- panda list --installed --verbose
script:
- prove -v -e "perl6 --ll-exception -Ilib" t/
