=pod

=encoding utf8

=head1 Name

MediaType

=head1 Synopsis

    use MediaType;
    my $ct-string = 'text/plain; charset=utf-8'
    my %results = MediaType::parse($ct-string);

    say %results<type>;                  # text
    say %results<params>.hash.<charset>; # utf-8

=head1 Description

Content-Type handler

L<http://tools.ietf.org/html/rfc6838>

=head1 Routines

=over

=item parse

Parse a content-type ct-string

=back

=cut
